#!/bin/bash

str=`ls ../res/webfiles`
echo $str
arr=($str)
declare -f arr



cd ../
./sbt package
rm ./res/domainAndTypo/*
for file in ${arr[@]}; do
	echo $file
	./sbt "run $file domainAndTypo/"
done
