#!/bin/bash

cd ../res/pairRecords

#lines=`diff -rqu distribution domainAndTypo | grep ^Only`
#str=${lines//Only in domainAndTypo: / }
str=`ls`
arrFile=($str)
declare -f arrDir

cd ../..
./sbt package
for file in ${arrFile[@]}; do
	echo $file
	#cd res/sortedWebFiles/$dir
	#str=`ls part-*`
	#arrFile=($str)
	#declare -f arrFile
	#cd ../../..
	#for file in ${arrFile[@]}; do
		#echo "$dir/$file"
		#./sbt "run $dir/$file pairRecords/"
	./sbt "run $file statistics/"
done
